### ISSUE TITLE
Error running on phone

### ISSUE THREAD

**Issue by taiyoOzora** [neoneye/SwiftyFORM#1]
Hi i got the following error when i tried running it on my iPhone 6 Plus... Is there any way to solve this problem? I ran the example app directly to test i get the same error as when i did it with my own app.

<img width="879" alt="screen shot 2015-07-12 at 4 55 31 pm" src="https://cloud.githubusercontent.com/assets/3457550/8637165/e95adafc-28b6-11e5-8cac-82fe3a36be2b.png">

**Comment by neoneye** [comment]
1. Create a breakpoint on "All Exceptions"
2. Run the app again
3. See where it stops

**Comment by neoneye** [comment]
Did this help locating the problem?

**Comment by taiyoOzora** [comment]
This doesnt seem to work
<img width="1920" alt="screen shot 2015-07-17 at 8 06 44 am" src="https://cloud.githubusercontent.com/assets/3457550/8737936/f16ce5c6-2c5a-11e5-8d3b-26081884c1ac.png">
<img width="1920" alt="screen shot 2015-07-17 at 8 06 54 am" src="https://cloud.githubusercontent.com/assets/3457550/8737937/f27ffcaa-2c5a-11e5-8d76-deaf4f9ad2ac.png">

**Comment by peyotll** [comment]
Same error here! It's in Swift 2 anyway... :/

**Comment by neoneye** [comment]
Please try again. I think I have fixed it. Sorry for the long delay. I don't have much spare time.

If you don't have an iOS9 device you can try out the [deployment_target_8_0](https://github.com/neoneye/SwiftyFORM/tree/deployment_target_8_0) branch.

**Comment by peyotll** [comment]
Thank you for this quick fix!
It now works on iOS 9 device but I'm not able to run it on 8.x (iOS version problem on device and missing library on simulator).
My goal is to integrate it in a project targetting 8.1+ devices. Would it work with the deployment_target_8_0 branch?

**Comment by neoneye** [comment]
try the deployment_target_8_0 branch. I don't think I use iOS9 specific features. It may work
