### ISSUE TITLE
install to my project

### ISSUE THREAD

**Issue by thanhhaiqtvn** [neoneye/SwiftyFORM#10]
How to install this framework to my project.
i using xcode 7.1.1
thank so much

**Comment by mofodox** [comment]
It would be great if we can install it via Cocoapods.

**Comment by MobileMon** [comment]
Open the project. Make sure swiftForm target selected (not example). Build for generic iOS device. Then pick a simulator and build for it. Now expand the Products folder and you should have your framework. See here for further instructions: https://www.youtube.com/watch?v=86cPaa3FrRg

**Comment by MobileMon** [comment]
Build the project with device type "Generic iOS Device"

Then expand the Products folder, in there will be your framework

See here for further help: https://www.youtube.com/watch?v=86cPaa3FrRg
