### ISSUE TITLE
OptionPickerFormItem has no 'value' property in DumpVisitor.dump()

### ISSUE THREAD

**Issue by skram** [neoneye/SwiftyFORM#12]
In the process of writing this issue, I've found that when dumping my form, my OptionPickerFormItem has no property value, I just solved it by adding dict["value"] = object.selected?.title in visitOptionPicker() . Might want to address it, unless this is the intended behavior? Thanks for this awesome framework!

**Comment by neoneye** [comment]
Thank you @skram for this fix
