### ISSUE TITLE
Custom validations

### ISSUE THREAD

**Issue by tawrahim** [neoneye/SwiftyFORM#14]
Is there a way to include custom validations in SwiftyForms?
An example would be checking if the values in `New Password` and `Repeat Password` Field matches.

It would be nice to be able to provide a function to the validate method

**Comment by neoneye** [comment]
[Specification Pattern](https://en.wikipedia.org/wiki/Specification_pattern) is used for validation. It allows multiple specifications to be combined.

In order to create validate you have to subclass `CompositeSpecification` and install this custom specification in the `TextFieldFormItem`.
