### ISSUE TITLE
Making it available via cocoapods.org

### ISSUE THREAD

**Issue by tawrahim** [neoneye/SwiftyFORM#15]
Any thoughts on making this project available via [Cocoa Pods](http://www.cocoapods.org)

**Comment by neoneye** [comment]
It's my plan. Well.. I haven't found time to do it yet. Perhaps I can find time soon.

**Comment by tawrahim** [comment]
Would you be okay if I go ahead and it?

**Comment by neoneye** [comment]
Sure 👍  and thank you @tawrahim

**Comment by tawrahim** [comment]
@neoneye I managed to add it this morning, you can take a look here [Cocoa Pods SwiftyFORM](https://cocoapods.org/?q=swiftyfo)
I am thinking that I should send you a PR for the changes to the README as well as the new .podspec that I added to merge into the main branch. Do you want me to make you the owner of the project on cocoapods.org?


Finally a slight off-topic question that I have regarding the usage of the library. Is there a way for me to just open the view controller by a user action? Example, I have a button in a regualr VC that I want when the user clicks on it to open lets say ChangePasswordViewController.swift

**Comment by neoneye** [comment]
Thank you @tawrahim very much. Looks great.

Me as the owner.. ok


Maybe like this?

```swift
func buttonAction() {
	let vc = ChangePasswordViewController()
	navigationController?.pushViewController(vc, animated: true)
}
```

**Comment by tawrahim** [comment]
@neoneye awesome for the snippet!
lol in terms of the merge, I think that would make more sense for the users of the library.
Should I go ahead and send a PR?

**Comment by neoneye** [comment]
yes please @tawrahim

**Comment by neoneye** [comment]
It's merged now and passes `pod lib lint`, Thank you @tawrahim much appreciated
