### ISSUE TITLE
TextViewFormItem and TextFieldFormItem are misaligned 

### ISSUE THREAD

**Issue by pboehm** [neoneye/SwiftyFORM#28]
At first, thank you for your work on this great library. It works like a charm!

The only problem I've encountered using version 1.2.0 is, that instances of TextViewFormItem and TextFieldFormItem are shown in full width compared to all other form items, as you can see from the attached screenshot. This problem occurs both on iPad and iPhone.

![img_0017](https://cloud.githubusercontent.com/assets/665684/22629732/67d9ea40-ebec-11e6-98c9-5557eb1f1e6d.PNG)

The code used to create the form is listed below:

```swift
    override func populate(_ builder: FormBuilder) {
        builder.navigationTitle = "Image Properties"
        builder += SectionHeaderTitleFormItem().title("Image Properties")
        builder += pickStatusFormField
        builder += starsFormField
        builder += colorFormField
        builder += titleFormField
        builder += subtitleFormField

        // ....
    }

    private lazy var titleFormField: TextViewFormItem = {
        let field = TextViewFormItem().title("Title")
        field.value = self.properties.title ?? ""
        return field
    }()

    private lazy var subtitleFormField: TextViewFormItem = {
        let field = TextViewFormItem().title("Subtitle")
        field.value = self.properties.subtitle ?? ""
        return field
    }()
```

**Comment by neoneye** [comment]
Thank you for submitting this issue. I'm investigating now.

**Comment by neoneye** [comment]
@pboehm I have updated `TextViewFormItem` and `TextFieldFormItem`, so that they now deal with 
`cellLayoutMarginsFollowReadableWidth`. Still there are a few more classes that needs to deal with it.

You can try if the new code works for you

If you have a podfile, you can paste the following snippet as it is. I have inserted the latest commit id, so you don't have to do it.

    pod 'SwiftyFORM', :git => 'https://github.com/neoneye/SwiftyFORM.git', :commit => '64c447a22a0502dd0d1658062145f24f243d80f5'

**Comment by neoneye** [comment]
I have made a 1.3.0 release, containing the changes.

**Comment by pboehm** [comment]
Thank you very much for this quick response and solution! I will try it asap.

**Comment by pboehm** [comment]
With version 1.3.1 the issue is gone. Thank you very much!
