### ISSUE TITLE
How do I manually validate a form?

### ISSUE THREAD

**Issue by VinvuSoftware** [neoneye/SwiftyFORM#29]
I'm trying to validate the form before I make an API call, however I can't seem to find out how the validator works. 

Sorry if this isn't the place to be posting this, I'm new to GitHub and iOS development in general. Is there a place I should be posting these questions? Also, is there documentation to your framework anywhere?

Thanks in advance!

**Comment by neoneye** [comment]
The best example code that shows how to validate is here:
https://github.com/neoneye/SwiftyFORM/blob/master/Example/Usecases/SignUpViewController.swift

The validation code uses the "Specification Pattern". Which is excellent for this purpose.
https://en.wikipedia.org/wiki/Specification_pattern

I'm sorry that there is little documentation.

**Comment by VinvuSoftware** [comment]
Ah great thank you, this already helps a lot!
