### ISSUE TITLE
how to force reload a form page?

### ISSUE THREAD

**Issue by iAladdin** [neoneye/SwiftyFORM#3]
@neoneye 

how to force reload a form in the same view controller?

when user change some conditions, I need reload the form.

Thank you!

**Comment by neoneye** [comment]
Take a look at `FormViewController.loadView()`.. use this

```
self.populate(formBuilder)
self.title = formBuilder.navigationTitle
dataSource = formBuilder.result(self)
self.tableView.dataSource = dataSource
self.tableView.delegate = dataSource
```

**Comment by iAladdin** [comment]
@neoneye Thank you, I wrapped it to a new function.
And I need remove all inner items first.

btw, is there a optional item?I didn't see it on example

**Comment by iAladdin** [comment]
@neoneye I use `CountSpecification.exactly(0)` to implement optional item

**Comment by neoneye** [comment]
There is no optional item. May be a good addition.
