### ISSUE TITLE
Can I use this without using the navigation controller ?

### ISSUE THREAD

**Issue by bojunwu** [neoneye/SwiftyFORM#30]
I'm using this for the settings in my project. It seems it can't call another viewcontroller unless I have a navigation controller in AppDelegat just like the example. Any solution ?
Thanks
Bojun

**Comment by neoneye** [comment]
That is a good question, Bojun.

The `ViewControllerFormItem` has assumptions about the navigation controller, inside the `PopulateTableView.visit(object: ViewControllerFormItem)` function. This code would be the right place to implement general purpose stuff, however it is difficult to modify.

Instead, I can recommend using the `ButtonFormItem`. This gives a button and an action handler, where you can custom present a view controller.

**Comment by bojunwu** [comment]
Thank you for the fast reply!
I thought about using ButtonFormItem too ! But it just can't display the way that normal cells do(the title is in the middle and it doesn't have the arrow like symbol). I have found ways to work around the problem. Thank you so much.
Cheers!
