### ISSUE TITLE
Multiple line for StaticTextFormItem

### ISSUE THREAD

**Issue by saxograph** [neoneye/SwiftyFORM#34]
I have StaticTextFormItem which has long, more than 200 characters, value. Is it possible to expand the form item so that the form item can show all value?

**Comment by neoneye** [comment]
Great question

Let me just check what to do

**Comment by neoneye** [comment]
You can use the `CustomFormItem` class.  Make your own multiline `UILabel` cell that implements the `CellHeightProvider` protocol.

In the Example project, take a look at the `CustomViewController` loading the `LoadingCell`.

Good luck, Hiroaki


Do you think multiline support would be a good addition to the `StaticTextFormItem` class?

**Comment by saxograph** [comment]
Perfect answer!
I will take a look the CustomFormItem and I believe I can implement what I want to do.

Yes, it would be good StaticTextFormItem supports multiple lines.

**Comment by neoneye** [comment]
I will have to think about how to add multiline support.

Thank you for valuable feedback, Hiroaki.

I will close this issue.
