### ISSUE TITLE
iPhone X - landscape

### ISSUE THREAD

**Issue by neoneye** [neoneye/SwiftyFORM#36]
tableview cells are not yet prepared for the iPhone X. The left and right inset is wrong.

![simulator screen shot - iphone x - 2017-09-12 at 22 12 46](https://user-images.githubusercontent.com/147971/30348599-e23a61da-9807-11e7-88e5-d960bee91f28.png)

**Comment by bradleymackey** [comment]
can be closed thanks to #46
