### ISSUE TITLE
How to add a image headerView ?

### ISSUE THREAD

**Issue by carlosbdw** [neoneye/SwiftyFORM#39]
I want  to add a 150x150 image at the top of the formviewcontroller, how could I ?

**Comment by neoneye** [comment]
Sorry there is no easy way to do it.

1. Take a look at the `CustomViewController.swift` file.
2. The `CustomFormItem` is used to create instances of the `LoaderCell`.
3. Replace `LoaderCell` with your own custom cell containing a `UIImageView`.

In the future, adding a dedicated imageview that seems like a good idea.
