### ISSUE TITLE
Change button color

### ISSUE THREAD

**Issue by PCrompton** [neoneye/SwiftyFORM#40]
Hi,

I'm looking for the proper way to change the background color for a ButtonFormItem, but there doesn't seem to be anything built into the framework, and I was wondering if there was a proper way to do this. I tried doing it while overriding reloadForm() but it didn't have my custom color the first time the view loaded.

Thanks,

-Paul

**Comment by neoneye** [comment]
There is currently no way to theme things. I'm open to suggestions/pull requests.

What you can do. In the example project, take a look at `CustomViewController.swift`. Here you can replace the `CustomFormItem` code with your custom button.

I'm sorry @PCrompton

**Comment by neoneye** [comment]
Thanks to @Pizzo15 the background color is now customizable. 

Example here: 
https://github.com/neoneye/SwiftyFORM/blob/master/Example/Other/ButtonsViewController.swift
