### ISSUE TITLE
Bug:  Cannot convert value of type

### ISSUE THREAD

**Issue by kristoff2016** [neoneye/SwiftyFORM#42]
Hello thanks for great plugin!
I got some error I do need your help: 

AttributedTextFormItem.swift:19:62: Cannot convert value of type '[String : AnyObject]?' to expected argument type '[NSAttributedStringKey : Any]?'

Thank you

**Comment by kristoff2016** [comment]
Need updated for swift 4 Thanks

**Comment by neoneye** [comment]
Thanks for the kind words @kristoff2016
