### ISSUE TITLE
Installed and removed a bunch of issues, but couldnt fix this one! Plz Help

### ISSUE THREAD

**Issue by chadbrochill317** [neoneye/SwiftyFORM#43]
Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

Can you please tell me how I can fix this? I recently installed and got a ton of errors, I am not sure why. I was able to solve them all, and this is the final one left. Please help!

**Comment by neoneye** [comment]
I have made SwiftyFORM in my spare time. Recently I migrated SwiftyFORM to work with the latest version of Xcode 10.1 (10B61).

Tell me more about your setup. 

What version do you have of: Xcode, Swift, SwiftyFORM ?

Post a version of your project online.

I'm available for consulting.

**Comment by chadbrochill317** [comment]
Hey man, sorry I jumped the gun posting this. I wasn’t running the pod in swift 4.2, now that I have updated swift and set the pod to 4.2 it works beautifully! Great work man, thanks for this!
