### ISSUE TITLE
Disable uppercase for Title?

### ISSUE THREAD

**Issue by IOS-Sisa** [neoneye/SwiftyFORM#51]
Hi there,

As your document/comment says "SectionHeaderTitleFormItem" only shows Uppercased string, I couldnt disable it. I really would like to show the string as it comes from service. 

How do i do that? Any tips?

**Comment by neoneye** [comment]
`SectionHeaderTitleFormItem` uses the default behavior of the `UITableViewDataSource.tableView(_ tableView: UITableView, titleForHeaderInSection section: Int)`, which is uppercasing.

Unfortunately `UITableView` is ugly when styling the headers/footers. This makes it tricky to do using SwiftyFORM. You can create a custom header using `SectionHeaderViewFormItem`. If you search for `demo_showInfo` inside the repo, there is an example of how to use `SectionHeaderViewFormItem`.

Does this work for you?
