### ISSUE TITLE
Min/Max for Stepper

### ISSUE THREAD

**Issue by justdan0227** [neoneye/SwiftyFORM#59]
Do we have the ability to set min and max for a StepperFormItem?

**Comment by neoneye** [comment]
There is no parameters for setting min/max values. How do you want the api for this to be like?

There is a `syncCellWithValue` callback where the value can be clamped.

**Comment by justdan0227** [comment]
Would be awesome if you could set a min/max like you do with

instance.submitValidate(CountSpecification.min(5), message: "Zipcode must be 5 numbers")

so maybe instance.minLimit(1) instance.maxLimit(5) ?

**Comment by neoneye** [comment]
IMHO steppers are for tiny values. For a 5 digit zipcode, perhaps use sheet with a number textfield, showing live the name of the area corresponding to the zipcode.

**Comment by gw-dkardell** [comment]
Thanks I was using a stepper for a review rating of 1-5
