### ISSUE TITLE
Return key goes to next cell.

### ISSUE THREAD

**Issue by Kowaio** [neoneye/SwiftyFORM#7]
Hello,

I was wondering if it was possible to go to the next cell while tapping the return key of the keyboard. I didn't find a method to do this in your example project yet from a TextFieldFormItem for instance.

Thanks a lot!

**Comment by neoneye** [comment]
great suggestion. I will consider this

**Comment by jbarros35** [comment]
You can integrate with already done keyboard libs.

**Comment by neoneye** [comment]
@jbarros35 Doesn't the return key already jump to the next cell. I can't remember, it's been a few years since I coded the functionality.
