### ISSUE TITLE
Inline datepicker 

### ISSUE THREAD

**Issue by JuseongJee** [neoneye/SwiftyFORM#8]
Hello!

UI Request.
What about Inline DatePicker like Calendar app in iOS?

**Comment by neoneye** [comment]
Great suggestion. I have seen it in one or two other form frameworks on CocoaControls.

Feel free to propose code for it and I will take a look at it :+1:

**Comment by JuseongJee** [comment]
I've seen some codes from 'http://github.com/KoheiHayakawa/KHAForm'

It uses cell def in file 'KHADatePickerFormCell.swift'
and when touching in date cell, show and hide date picker view cell for various situation in the file 'KHAFormViewController.swift'

i'm very sorry that i cannot apply it to SwiftyForm and contribute.
it's hard for me :(

**Comment by neoneye** [comment]
KHAForm example gif looks pretty good. Thank you for the link

**Comment by neoneye** [comment]
Hi @JuseongJee 

I have just implemented inline date pickers.

Cheers

**Comment by JuseongJee** [comment]
Oh!
Great! :)
